# docker exec $(docker ps -lq) /bin/bash -c "wp db import /data/database.sql --allow-root"

version: '2'
services:
    database:
        container_name: odyssey-mysql
        image: mysql:5.7
        env_file:
            - .env
        ports:
            - "3306:3306"
    webserver:
        container_name: odyssey-webserver
        build:
            context: .
            dockerfile: .docker/webserver/Dockerfile
        volumes:
            - .:/var/www/odyssey
        links:
            - database
        depends_on:
            - database
        env_file:
            - .env
        ports:
            - "80:80"