# docker exec $(docker ps -lq) /bin/bash -c "wp db import /data/database.sql --allow-root"

version: '2'
services:
    database:
        container_name: odyssey-mysql
        image: mysql:5.7.16
        env_file:
            - .env
        ports:
            - "3306:3306"
    webserver:
        container_name: odyssey-webserver
        build:
            context: .
            dockerfile: .docker/webserver/Dockerfile
        volumes:
            - ${PWD}:/var/www/odyssey
            # Ignore NPM and Bower packages:
            # Prevent the mounting above from overwriting the app.
            # https://github.com/docker/compose/issues/1607#issuecomment-240458538
            - /var/www/odyssey/wp-content/themes/odyssey/node/node_modules
            - /var/www/odyssey/wp-content/themes/odyssey/node/bower_components
        links:
            - database
        depends_on:
            - database
        env_file:
            - .env
        ports:
            - "80:80"