<?php

if (function_exists("register_field_group"))
{
    register_field_group(array(
        'id'         => 'acf_banner',
        'title'      => 'Banner',
        'fields'     => array(
            array(
                'key'          => 'field_58c15679c1b2a',
                'label'        => 'Image',
                'name'         => 'banner_image',
                'type'         => 'image',
                'required'     => 1,
                'save_format'  => 'object',
                'preview_size' => 'thumbnail',
                'library'      => 'all',
            ),
            array(
                'key'        => 'field_58c1576ec3509',
                'label'      => 'Link',
                'name'       => 'banner_link',
                'type'       => 'page_link',
                'post_type'  => array(
                    0 => 'post',
                    1 => 'page',
                ),
                'allow_null' => 0,
                'multiple'   => 0,
            ),
        ),
        'location'   => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'banner',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options'    => array(
            'position'       => 'normal',
            'layout'         => 'default',
            'hide_on_screen' => array(
                0  => 'permalink',
                1  => 'the_content',
                2  => 'excerpt',
                3  => 'custom_fields',
                4  => 'discussion',
                5  => 'comments',
                6  => 'revisions',
                7  => 'slug',
                8  => 'author',
                9  => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id'         => 'acf_services',
        'title'      => 'Services',
        'fields'     => array(
            array(
                'key'           => 'field_58c15b92787c3',
                'label'         => 'Icon',
                'name'          => 'service_icon',
                'type'          => 'text',
                'instructions'  => 'Click <a href="https://developer.wordpress.org/resource/dashicons" target="_blank">here</a> to see the available options.',
                'required'      => 1,
                'default_value' => '',
                'placeholder'   => 'media-audio',
                'prepend'       => 'dashicons-',
                'append'        => '',
                'formatting'    => 'none',
                'maxlength'     => '',
            ),
            array(
                'key'           => 'field_58c15c29787c4',
                'label'         => 'Description',
                'name'          => 'service_description',
                'type'          => 'textarea',
                'required'      => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'formatting'    => 'br',
            ),
        ),
        'location'   => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'services',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options'    => array(
            'position'       => 'normal',
            'layout'         => 'default',
            'hide_on_screen' => array(
                0  => 'permalink',
                1  => 'the_content',
                2  => 'excerpt',
                3  => 'custom_fields',
                4  => 'discussion',
                5  => 'comments',
                6  => 'revisions',
                7  => 'slug',
                8  => 'author',
                9  => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array(
        'id'         => 'acf_team-member',
        'title'      => 'Team Member',
        'fields'     => array(
            array(
                'key'          => 'field_58c159f01f57f',
                'label'        => 'Picture',
                'name'         => 'team_picture',
                'type'         => 'image',
                'required'     => 1,
                'save_format'  => 'object',
                'preview_size' => 'thumbnail',
                'library'      => 'all',
            ),
            array(
                'key'           => 'field_58c15a7b4d20b',
                'label'         => 'Mini Resume',
                'name'          => 'team_resume',
                'type'          => 'textarea',
                'required'      => 1,
                'default_value' => '',
                'placeholder'   => '',
                'maxlength'     => '',
                'rows'          => '',
                'formatting'    => 'br',
            ),
        ),
        'location'   => array(
            array(
                array(
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'team-member',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options'    => array(
            'position'       => 'normal',
            'layout'         => 'default',
            'hide_on_screen' => array(
                0  => 'permalink',
                1  => 'the_content',
                2  => 'excerpt',
                3  => 'custom_fields',
                4  => 'discussion',
                5  => 'comments',
                6  => 'revisions',
                7  => 'slug',
                8  => 'author',
                9  => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
}
